# Generated by Django 5.2.8 on 2025-11-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('R', 'En revisión'), ('C', 'Completada')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], max_length=10),
        ),
    ]
