# Generated by Django 5.2.8 on 2025-11-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_add_proyecto_fields'),
        ('proyectos', '0002_remove_tarea_fecha_creacion_tarea_estado_and_more'),
    ]

    operations = [
    ]
