# Generated by Django 5.2.8 on 2025-11-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE', 'Jefe de proyecto'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, help_text='Ignorado, usamos email para login.', max_length=150, null=True),
        ),
    ]
